```{r}
library(magrittr) 
library(dplyr)    
library(tidyr)
library('arules') 
```


```{r}
#Selección de atributos, año 2019
datos_2019<-read.csv(file = "datos_limpios/2019.csv", sep = ",")[ ,c("jornada","rango_edad","dur_total_carr","tipo_inst_3","area_conocimiento","region_sede","acreditada_inst","valor_arancel","valor_matricula")]
```

```{r}
#Muestra del 30% de los datos
sample<-datos_2019 %>% sample_frac(.3)
complete_sample<-sample[complete.cases(sample),]
```

```{r}
#Creación de categorías por percentiles para el valor de arancel
Percentile_00  = min(complete_sample$valor_arancel)
Percentile_33  = quantile(complete_sample$valor_arancel, 0.33333)
Percentile_67  = quantile(complete_sample$valor_arancel, 0.66667)
Percentile_100 = max(complete_sample$valor_arancel)

RB = rbind(Percentile_00, Percentile_33, Percentile_67, Percentile_100)

dimnames(RB)[[2]] = "Value"
```

```{r}
#Creación de categorías por percentiles para el valor de matrícula
PercentileM_00  = min(complete_sample$valor_matricula)
PercentileM_33  = quantile(complete_sample$valor_matricula, 0.33333)
PercentileM_67  = quantile(complete_sample$valor_matricula, 0.66667)
PercentileM_100 = max(complete_sample$valor_matricula)

RBM = rbind(PercentileM_00, PercentileM_33, PercentileM_67, PercentileM_100)

dimnames(RBM)[[2]] = "Value"
```

```{r}
complete_sample$Categoria_arancel[complete_sample$valor_arancel >= Percentile_00 & complete_sample$valor_arancel <  Percentile_33]  = "AB"
complete_sample$Categoria_arancel[complete_sample$valor_arancel >= Percentile_33 & complete_sample$valor_arancel <  Percentile_67]  = "AM"
complete_sample$Categoria_arancel[complete_sample$valor_arancel >= Percentile_67 & complete_sample$valor_arancel <= Percentile_100] = "AA"
complete_sample$valor_arancel <- NULL
```


```{r}
complete_sample$Categoria_matricula[complete_sample$valor_matricula >= PercentileM_00 & complete_sample$valor_matricula <  PercentileM_33]  = "MB"
complete_sample$Categoria_matricula[complete_sample$valor_matricula >= PercentileM_33 & complete_sample$valor_matricula <  PercentileM_67]  = "MM"
complete_sample$Categoria_matricula[complete_sample$valor_matricula >= PercentileM_67 & complete_sample$valor_matricula <= PercentileM_100] = "MA"
complete_sample$valor_matricula <- NULL
```

```{r}
#CSV con atributos seleccionados
write.csv(complete_sample,"datos_limpios/2019_sample_30%.csv", row.names = FALSE)
```


```{r, eval=T, warning=F}
df <- read.transactions("datos_limpios/2019_sample_30%.csv", sep=",")
```

```{r}
frequentItems <- eclat(df, parameter = list(supp = 0.4))
items.sorted <- sort(frequentItems, by="support")
inspect(head(items.sorted))
```

```{r}
# Se utiliza apriori para encontrar reglas de asociación de itemset frecuentes de 4 items con support 4% y confidence 30%
rules <- apriori(df, parameter=list(support=0.04, confidence=0.3),minlen=4)
rules.sorted <- sort(rules, by="lift")
rules.sorted.first10 <- head(rules.sorted, 10)
inspect(rules.sorted.first10)
```
```{r}
plot(rules, measure=c("support", "confidence"), shading="lift", interactive=FALSE, main= "Scatter plot para 2001 reglas de asociación")
```

```{r}
AA_rules <- subset(rules, items %in% "AA", by= "support")
inspect(head(AA_rules))
```

```{r}
plot(AA_rules,method="graph",interactive=FALSE,shading="lift")
title(main = "Arancel Alto")
```
```{r}
plot(AA_rules, method="paracoord")
```
```{r}
plot(AA_rules, method = "paracoord", control = list(reorder = TRUE))
```

```{r}
plot(head(AA_rules, n=1000, by= "lift"), method = "graph")
```

```{r}
AM_rules <- subset(rules, items %in% "AM", by= "support")
inspect(head(AM_rules))
```


```{r}
AB_rules <- subset(rules, items %in% "AB", by= "support")
rhs_AB_rules <- sort(subset(rules, subset = rhs %in% "AB"), by = "lift")
inspect(head(rhs_AB_rules))
```


```{r}
rhs_AA_rules <- sort(subset(rules, subset = rhs %in% "AA"), by = "lift")
inspect(rhs_AA_rules)
```
```{r}
plot(rhs_AA_rules,method="graph",interactive=FALSE,shading="lift")
title(main = "Reglas que implican Arancel Alto 2019")
```
```{r}
plot(rhs_AB_rules,method="graph",interactive=FALSE,shading="lift")
title(main = "Reglas que implican Arancel Bajo 2019")
```

```{r}

rhs_MB_rules <- sort(subset(rules, subset = rhs %in% "MB"), by = "lift")
inspect(rhs_MB_rules)

```


